data:
  evfile : PG1553.lst
  scfile : data/L211025154921445A2D9929_SC00.fits

binning:
  roiwidth   : 10.0
  binsz      : 0.1
  binsperdec : 8

selection :
  emin : 100
  emax : 300000
  zmax    : 90
  evclass : 128
  evtype  : 3
  target : 'PG 1553+113'

gtlike:
  edisp : True
  irfs : 'P8R2_SOURCE_V6'
  edisp_disable : ['isodiff','galdiff']

model:
  src_roiwidth : 15.0
  galdiff  : 'diffuse/gll_iem_v07.fits'
  isodiff  : 'diffuse/iso_P8R2_SOURCE_V6_v06.txt'
  catalogs : ['4FGL']
  
