name: PHYS3009_fermipy
channels:
  - fermi
  - conda-forge
dependencies:
  - python=3.7
  - pyyaml
  - numpy=1.20
  - scipy=1.6.1
  - astropy=4.2
  - matplotlib=3.3.4
  - healpy=1.14
  - astropy-healpix=0.6
  - gammapy=0.18
  - fermitools=2.0
  - fermipy
