name: fermipy
channels:
  - fermi
  - conda-forge
dependencies:
  - python
  - pyyaml
  - numpy=1.20
  - scipy<1.6.2
  - astropy<4.3
  - matplotlib<3.4
  - healpy
  - astropy-healpix
  - gammapy=0.18
  - fermitools=2.0.8
  